[build]
command = "rustup default stable && cargo install mdbook && npm install && npm run build"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/std/*"
[headers.values]
Content-Type = "text/plain"
