[build.environment]    
NPM_FLAGS = "--version"

[build]
command = "./build.sh"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/std/*"

[headers.values]
Content-Type = "text/plain"
